import type { FlowContext, ScreenId } from '../types/flow'
import { MILEAGE_SCENARIOS, TRUSTED_MILEAGE_STATE } from './mileageScenarios'
import { VSA_VEHICLE } from './vehicleSummary'

export const INITIAL_CONTEXT: FlowContext = {
  screen: 'fueling-default',
  movementComplete: true,
  movementMode: 'transport',
  movementPhase: 'location-selected',
  location: 'Albany AP QTA',
  stallNumber: '',
  stallPhase: 'select-stall',
  stallSectionNumber: '',
  fuelComplete: false,
  stallComplete: false,
  cleaningComplete: false,
  cleaningStep: 'verify-pump',
  cleaningPumpNumber: '',
  cleaningStartedAt: null,
  cleaningFinalTime: '',
  fuelStep: 'verify-pump',
  pumpNumber: '',
  fuelGallons: '',
  fuelGallonsDispensed: '5',
  fuelFinalTime: '',
  fuelStartedAt: null,
  isAdditionalFueling: false,
  fuelTransactions: [],
  unavailablePumps: [3, 6],
  showIssueOverlay: false,
  issueDetails: '',
  issueReportSource: null,
  unlockMode: 'remote',
  locationType: 'gasboy',
  odometerReading: '',
  mileageState: TRUSTED_MILEAGE_STATE,
}

const TRANSPORT_WORKFLOW_BASE: Partial<FlowContext> = {
  movementComplete: false,
  movementMode: 'transport',
  movementPhase: 'select-location',
  location: '',
  stallNumber: '',
  fuelComplete: false,
  stallComplete: false,
  fuelStep: 'verify-pump',
  pumpNumber: '',
  fuelGallons: '',
  fuelStartedAt: null,
  isAdditionalFueling: false,
  fuelTransactions: [],
  unlockMode: 'remote',
  locationType: 'gasboy',
  showIssueOverlay: false,
  issueDetails: '',
  odometerReading: '',
}

const VSA_WORKFLOW_BASE: Partial<FlowContext> = {
  movementComplete: true,
  movementMode: 'transport',
  movementPhase: 'location-selected',
  location: 'Albany AP QTA',
  stallNumber: '',
  cleaningComplete: false,
  cleaningStep: 'verify-pump',
  cleaningPumpNumber: '',
  cleaningStartedAt: null,
  cleaningFinalTime: '',
  fuelComplete: false,
  fuelStep: 'verify-pump',
  pumpNumber: '',
  fuelGallons: '',
  fuelStartedAt: null,
  isAdditionalFueling: false,
  fuelTransactions: [],
  stallPhase: 'select-stall',
  stallSectionNumber: '',
  stallComplete: false,
  unlockMode: 'remote',
  locationType: 'gasboy',
  vsaStallEnabled: true,
  showIssueOverlay: false,
  issueDetails: '',
  issueReportSource: null,
  odometerReading: '',
  mileageState: VSA_VEHICLE.mileageState,
  fuelSimAutoCompleteMs: VSA_VEHICLE.fuelSimulation?.autoCompleteMs,
  fuelSimPumpStatusDelayMs: VSA_VEHICLE.fuelSimulation?.pumpStatusDelayMs,
  fuelSimGallons: VSA_VEHICLE.fuelSimulation?.gallons,
}

const MILEAGE_SCREEN_PRESETS = Object.fromEntries(
  Object.entries(MILEAGE_SCENARIOS).map(([id, scenario]) => [
    id,
    {
      ...TRANSPORT_WORKFLOW_BASE,
      mileageState: scenario.state,
      odometerReading: '',
    },
  ]),
) as Record<keyof typeof MILEAGE_SCENARIOS, Partial<FlowContext>>

export const SCREEN_PRESETS: Record<ScreenId, Partial<FlowContext>> = {
  'transport-default': {
    ...TRANSPORT_WORKFLOW_BASE,
    mileageState: TRUSTED_MILEAGE_STATE,
  },
  'transport-complete': {
    movementComplete: true,
    movementMode: 'transport',
    movementPhase: 'location-selected',
    location: 'Albany AP QTA',
    stallNumber: '',
    fuelComplete: true,
    stallComplete: true,
    fuelStep: 'fueling-complete',
    showIssueOverlay: false,
    mileageState: TRUSTED_MILEAGE_STATE,
  },
  'transport-issue-header': {
    ...TRANSPORT_WORKFLOW_BASE,
    mileageState: TRUSTED_MILEAGE_STATE,
    movementComplete: true,
    movementPhase: 'location-selected',
    location: 'Albany AP QTA',
    showIssueOverlay: true,
    issueDetails: '',
    issueReportSource: 'header',
  },
  'movement-transport-location-selected': {
    ...TRANSPORT_WORKFLOW_BASE,
    mileageState: TRUSTED_MILEAGE_STATE,
    movementComplete: false,
    movementPhase: 'location-selected',
    location: 'Albany AP QTA',
    fuelComplete: false,
    fuelStep: 'verify-pump',
    showIssueOverlay: false,
  },
  'movement-transport-complete': {
    movementComplete: true,
    movementMode: 'transport',
    movementPhase: 'location-selected',
    location: 'Albany AP QTA',
    stallNumber: '',
    fuelComplete: false,
    stallComplete: false,
    fuelStep: 'verify-pump',
    showIssueOverlay: false,
  },
  'movement-stall-select-stall': {
    ...TRANSPORT_WORKFLOW_BASE,
    mileageState: TRUSTED_MILEAGE_STATE,
    movementComplete: false,
    movementMode: 'stall',
    movementPhase: 'select-stall',
    location: '',
    stallNumber: '',
    fuelComplete: false,
    fuelStep: 'verify-pump',
    showIssueOverlay: false,
  },
  'movement-stall-complete': {
    movementComplete: true,
    movementMode: 'stall',
    movementPhase: 'stall-selected',
    location: '',
    stallNumber: '5',
    fuelComplete: false,
    stallComplete: false,
    fuelStep: 'verify-pump',
    showIssueOverlay: false,
  },
  'movement-stall-stall-verify': {
    ...TRANSPORT_WORKFLOW_BASE,
    mileageState: TRUSTED_MILEAGE_STATE,
    movementComplete: false,
    movementMode: 'stall',
    movementPhase: 'stall-verify',
    location: '',
    stallNumber: '5',
    fuelComplete: false,
    fuelStep: 'verify-pump',
    showIssueOverlay: false,
  },
  'movement-stall-issue-reported': {
    movementComplete: true,
    movementMode: 'stall',
    movementPhase: 'stall-issue-reported',
    location: '',
    stallNumber: '5',
    fuelComplete: false,
    stallComplete: false,
    fuelStep: 'verify-pump',
    showIssueOverlay: false,
  },
  'vsa-complete': {
    ...VSA_WORKFLOW_BASE,
    cleaningComplete: true,
    cleaningStep: 'cleaning-complete',
    cleaningFinalTime: '00:12:45',
    fuelComplete: true,
    fuelStep: 'fueling-complete',
    pumpNumber: '8',
    fuelGallonsDispensed: '5',
    fuelTransactions: [{ pump: '8', gallons: '5', status: 'complete' }],
    stallPhase: 'stall-selected',
    stallSectionNumber: '5',
    stallComplete: true,
  },
  'vsa-issue-header': {
    ...VSA_WORKFLOW_BASE,
    showIssueOverlay: true,
    issueDetails: '',
    issueReportSource: 'header',
  },
  'cleaning-default': {
    ...VSA_WORKFLOW_BASE,
    cleaningStep: 'verify-pump',
    cleaningPumpNumber: '',
  },
  'cleaning-manual-entry': {
    ...VSA_WORKFLOW_BASE,
    cleaningStep: 'manual-entry',
    cleaningPumpNumber: '',
  },
  'cleaning-manual-entry-filled': {
    ...VSA_WORKFLOW_BASE,
    cleaningStep: 'manual-entry-filled',
    cleaningPumpNumber: '5',
  },
  'cleaning-manual-entry-error': {
    ...VSA_WORKFLOW_BASE,
    cleaningStep: 'manual-entry-error',
    cleaningPumpNumber: '3',
  },
  'cleaning-pump-verified': {
    ...VSA_WORKFLOW_BASE,
    cleaningStep: 'pump-verified',
    cleaningPumpNumber: '5',
  },
  'cleaning-in-progress': {
    ...VSA_WORKFLOW_BASE,
    cleaningStep: 'cleaning-in-progress',
    cleaningPumpNumber: '5',
    cleaningStartedAt: Date.now() - 120_000,
  },
  'cleaning-complete': {
    ...VSA_WORKFLOW_BASE,
    cleaningComplete: true,
    cleaningStep: 'cleaning-complete',
    cleaningPumpNumber: '5',
    cleaningFinalTime: '00:12:45',
    cleaningStartedAt: Date.now() - 765_000,
  },
  'stall-default': {
    ...VSA_WORKFLOW_BASE,
  },
  'vsa-no-stall-default': {
    ...VSA_WORKFLOW_BASE,
    vsaStallEnabled: false,
    locationType: 'non-gasboy',
    unlockMode: 'on-site',
    fuelStep: 'verify-pump',
  },
  'stall-complete': {
    ...VSA_WORKFLOW_BASE,
    fuelComplete: true,
    fuelStep: 'fueling-complete',
    stallPhase: 'stall-selected',
    stallSectionNumber: '5',
    stallComplete: true,
  },
  'stall-missing': {
    ...VSA_WORKFLOW_BASE,
    fuelComplete: true,
    fuelStep: 'fueling-complete',
    stallPhase: 'stall-verify',
    stallSectionNumber: '5',
    stallComplete: false,
  },
  'stall-issue-reported': {
    ...VSA_WORKFLOW_BASE,
    fuelComplete: true,
    fuelStep: 'fueling-complete',
    stallPhase: 'stall-issue-reported',
    stallSectionNumber: '5',
    stallComplete: true,
  },
  'fueling-default': {
    movementComplete: true,
    movementMode: 'transport',
    movementPhase: 'location-selected',
    location: 'Albany AP QTA',
    stallNumber: '',
    fuelComplete: false,
    stallComplete: false,
    fuelStep: 'verify-pump',
    unlockMode: 'remote',
    locationType: 'gasboy',
    showIssueOverlay: false,
  },
  'fueling-unlocking': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'unlocking-pump',
    pumpNumber: '12',
    showIssueOverlay: false,
  },
  'fueling-scanner': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'verify-pump',
    showIssueOverlay: false,
  },
  'fueling-manual-entry': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'manual-entry',
    pumpNumber: '',
    showIssueOverlay: false,
  },
  'fueling-pump-unlocked': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'fueling-in-progress',
    pumpNumber: '12',
    fuelStartedAt: Date.now() - 15_000,
    fuelPumpStatusReceived: false,
    showIssueOverlay: false,
    screen: 'fueling-in-progress',
  },
  'fueling-in-progress': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'fueling-in-progress',
    pumpNumber: '12',
    fuelStartedAt: Date.now() - 15_000,
    fuelPumpStatusReceived: false,
    showIssueOverlay: false,
  },
  'fueling-in-progress-unconfirmed': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'fueling-in-progress',
    pumpNumber: '12',
    fuelStartedAt: Date.now() - 20_000,
    fuelPumpStatusReceived: true,
    showIssueOverlay: false,
  },
  'fueling-complete': {
    movementComplete: true,
    fuelComplete: true,
    fuelStep: 'fueling-complete',
    pumpNumber: '8',
    fuelGallonsDispensed: '5',
    fuelFinalTime: '00:01:14',
    fuelTransactions: [{ pump: '8', gallons: '5', status: 'complete' }],
    showIssueOverlay: false,
  },
  'fueling-additional': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'verify-pump',
    pumpNumber: '',
    isAdditionalFueling: true,
    fuelTransactions: [{ pump: '8', gallons: '5', status: 'issue' }],
    showIssueOverlay: false,
  },
  'fueling-additional-complete': {
    movementComplete: true,
    fuelComplete: true,
    fuelStep: 'additional-fueling-complete',
    pumpNumber: '12',
    fuelGallonsDispensed: '3',
    fuelFinalTime: '00:02:08',
    isAdditionalFueling: true,
    fuelTransactions: [
      { pump: '8', gallons: '5', status: 'issue' },
      { pump: '12', gallons: '3', status: 'complete' },
    ],
    showIssueOverlay: false,
  },
  'fueling-pump-unavailable': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'pump-unavailable',
    showIssueOverlay: false,
  },
  'fueling-connection-lost': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'connection-lost',
    pumpNumber: '12',
    showIssueOverlay: false,
  },
  'fueling-no-response': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'no-response',
    pumpNumber: '12',
    showIssueOverlay: false,
  },
  'fueling-pump-timeout': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'pump-timeout',
    pumpNumber: '12',
    showIssueOverlay: false,
  },
  'fueling-issue': {
    movementComplete: true,
    fuelComplete: true,
    fuelStep: 'fueling-complete',
    pumpNumber: '12',
    showIssueOverlay: true,
    issueDetails: '',
  },
  'fueling-issue-details': {
    movementComplete: true,
    fuelComplete: true,
    fuelStep: 'fueling-complete',
    pumpNumber: '12',
    showIssueOverlay: true,
    issueDetails: '',
  },
  'on-site-default': {
    movementComplete: true,
    movementMode: 'transport',
    movementPhase: 'location-selected',
    location: 'Albany AP QTA',
    stallNumber: '',
    fuelComplete: false,
    stallComplete: false,
    fuelStep: 'verify-pump',
    pumpNumber: '',
    unlockMode: 'on-site',
    locationType: 'gasboy',
    showIssueOverlay: false,
  },
  'on-site-manual-entry': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'manual-entry',
    pumpNumber: '',
    unlockMode: 'on-site',
    locationType: 'gasboy',
    showIssueOverlay: false,
  },
  'on-site-pump-verified': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'pump-verified',
    pumpNumber: '2',
    unlockMode: 'on-site',
    locationType: 'gasboy',
    showIssueOverlay: false,
  },
  'on-site-fueling-in-progress': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'fueling-in-progress',
    pumpNumber: '8',
    unlockMode: 'on-site',
    fuelStartedAt: Date.now() - 74_000,
    fuelGallons: '',
    showIssueOverlay: false,
  },
  'on-site-fueling-complete': {
    movementComplete: true,
    fuelComplete: true,
    fuelStep: 'fueling-complete',
    pumpNumber: '8',
    unlockMode: 'on-site',
    showIssueOverlay: false,
  },
  'on-site-missing-info': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'fueling-complete-missing',
    pumpNumber: '8',
    fuelGallons: '',
    fuelGallonsDispensed: '',
    fuelFinalTime: '00:01:14',
    stallComplete: false,
    unlockMode: 'on-site',
    locationType: 'gasboy',
    showIssueOverlay: false,
  },
  'on-site-missing-filled': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'fueling-complete-missing',
    pumpNumber: '8',
    fuelGallons: '5',
    fuelGallonsDispensed: '',
    fuelFinalTime: '00:01:14',
    stallComplete: false,
    unlockMode: 'on-site',
    locationType: 'gasboy',
    showIssueOverlay: false,
  },
  'non-gasboy-default': {
    movementComplete: true,
    movementMode: 'transport',
    movementPhase: 'location-selected',
    location: 'Albany AP QTA',
    stallNumber: '',
    fuelComplete: false,
    stallComplete: false,
    fuelStep: 'verify-pump',
    pumpNumber: '',
    unlockMode: 'remote',
    locationType: 'non-gasboy',
    showIssueOverlay: false,
  },
  'non-gasboy-manual-entry': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'manual-entry',
    pumpNumber: '',
    locationType: 'non-gasboy',
    showIssueOverlay: false,
  },
  'non-gasboy-pump-verified': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'pump-verified',
    pumpNumber: '4',
    locationType: 'non-gasboy',
    showIssueOverlay: false,
  },
  'non-gasboy-fueling-in-progress': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'fueling-in-progress',
    pumpNumber: '4',
    locationType: 'non-gasboy',
    fuelStartedAt: Date.now() - 74_000,
    fuelGallons: '',
    showIssueOverlay: false,
  },
  'non-gasboy-fueling-complete': {
    movementComplete: true,
    fuelComplete: true,
    fuelStep: 'fueling-complete',
    pumpNumber: '4',
    locationType: 'non-gasboy',
    showIssueOverlay: false,
  },
  'non-gasboy-missing-info': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'fueling-complete-missing',
    pumpNumber: '8',
    fuelGallons: '',
    fuelGallonsDispensed: '',
    fuelFinalTime: '00:01:14',
    stallComplete: false,
    locationType: 'non-gasboy',
    showIssueOverlay: false,
  },
  'non-gasboy-missing-filled': {
    movementComplete: true,
    fuelComplete: false,
    fuelStep: 'fueling-complete-missing',
    pumpNumber: '8',
    fuelGallons: '5',
    fuelGallonsDispensed: '',
    fuelFinalTime: '00:01:14',
    stallComplete: false,
    locationType: 'non-gasboy',
    showIssueOverlay: false,
  },
  ...MILEAGE_SCREEN_PRESETS,
}

export function buildFlowContextForScreen(screen: ScreenId): FlowContext {
  return {
    ...INITIAL_CONTEXT,
    ...SCREEN_PRESETS[screen],
    screen,
  }
}

export function mergeScreenPreset(
  prev: FlowContext,
  screen: ScreenId,
): FlowContext {
  return {
    ...prev,
    ...SCREEN_PRESETS[screen],
    screen,
  }
}
